# version: '3.8'
services:
  postgres:
    image: postgres:16.4-bookworm
    restart: always
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=webapi
    ports:
      - "5432:5432"
